extends Node

enum build_ons { COMBUSTION_ENGINE, CONDENSED_BATTERY, EFFICIENT_ENGINE, ENERGY_BRACER, FIREPROOF_CHASSIS, HEAVY_BATTERY, HYDROLIC_ENGINE, JET_PROPULSION, MECHANICAL_ARM, MEGA_HOSE, SMOTHER_BLANKET, SOLAR_BATTERY }
enum cutscene_type { CLIMB_UP, LEAVE_STATION, FINISH }
